config/routes.rb
Messenger::Application.routes.draw do
  resources :password_reset, only: [:new, :edit, :create, :update]

  root :to => 'static_pages#home'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, except: [:index, :update]

  get 'inbox', :to => 'messages#inbox'
  get 'outbox', :to => 'messages#outbox'

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :require_login, :except => [:current_users_list, :home]

  helper_method :current_users_list, :active_users

  def home
    respond_to do |format|
      format.html
    end
  end

  def current_users_list
    current_users.map {|u| u.fname + ' ' + u.lname}.join(', ')
  end

  def active_users
    current_users
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1><%= t('home.jumbo.title') %></h1>
  <%# TODO: bug. Message- in text instead of Messenger- %>
  <p><%=  t('home.jumbo.text') %></p>
  <% if !current_user %><p><%= link_to t('home.jumbo.btn_signup'), new_user_path, :class => 'btn btn-primary btn-lg' %></p><% end %>
</div>

<div class="panel panel-default">
  <%# TODO: bug. when 1 user online, text is still pluralized %>
  <div class="panel-heading"><%= "#{active_users.count} users are currently online:" %></div>
  <div class="panel-body">
    <%= raw(active_users.map {|u| link_to "#{u.fname} #{u.lname}", user_path(u)}.join(', ')) %>
  </div>
</div>