config/routes.rb
Messenger::Application.routes.draw do
  resources :password_reset, only: [:new, :edit, :create, :update]

  root :to => 'static_pages#home'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, except: [:index, :update]

  get 'inbox', :to => 'messages#inbox'
  get 'outbox', :to => 'messages#outbox'

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout

end

app/models/message.rb
class Message
  include Mongoid::Document

  before_save :set_time

  field :to, :type => String
  field :from, :type => String
  field :subject, :type => String
  field :content, :type => String
  field :created_at, :type => DateTime#, default: ->{ Time.now }
  field :unread, :type => Boolean, :default => true

  attr_accessible :to, :from, :subject, :content, :unread
  # TODO: bug. created_at is not read-only. will be updated on removing unread flag.
  attr_readonly :to, :from, :subject, :content#, :created_at

  validates_presence_of :to, :from, :subject, :content

  validates_length_of :subject, :maximum => 100
  validates_length_of :content, :maximum => 1000

  private
  def set_time
    self.created_at = Time.now
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def inbox
    @messages = Message.where(:to => current_user.email).order_by([:created_at, :desc])
    @title = t('app_name') + ' | ' + t('messages.inbox.title')

    respond_to do |format|
      format.html # inbox.html.erb
      format.json { render json: @messages }
    end
  end

  def outbox
    # TODO: bug. messages incorrectly ordered
    @messages = Message.where(:from => current_user.email)#.order_by([:created_at, :desc])
    @title = t('app_name') + ' | ' + t('messages.outbox.title')

    respond_to do |format|
      format.html # outbox.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    @message.update_attributes!(:unread => false) if (@message.to == current_user.email)
    @from = User.where(:email => @message.from).first
    @to = User.where(:email => @message.to).first
    @title = t('app_name') + ' | ' + t('messages.show.title')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new
    @reply_to = params[:reply_to]
    @title = t('app_name') + ' | ' + t('messages.new.title')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.from = current_user.email

    respond_to do |format|
      if @message.save
        format.html { redirect_to inbox_url, notice: t('messages.create.notice') }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.to == current_user.email
        @message.destroy
        format.html { redirect_to inbox_url }
        format.json { head :no_content }
      else
        format.html { redirect_to inbox_url, error: t('messages.destroy.error') }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

  def inbox_count
    current_user ? Message.where(:to => current_user.email).count : 0
  end

  def outbox_count
    current_user ? Message.where(:from => current_user.email).count : 0
  end

  def recipients
    # TODO: bug. all users in recipients list. only active should present
    User.all
    #User.where(:activation_state => 'active')
  end

  def user_path_by_email(email)
    user = User.where(:email => email).first
    user_path(user) if user
  end
end

app/views/messages/_lsidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <%= nav_link(raw(t('messages.sidebar.inbox') + ' <span class="badge pull-right">' + inbox_count.to_s + '</span>'), inbox_path) %>
  <%= nav_link(raw(t('messages.sidebar.outbox') + ' <span class="badge pull-right">' + outbox_count.to_s + '</span>'), outbox_path) %>
</ul>

app/views/messages/_msg_list.html.erb
<% is_inbox = current_page?(inbox_path) %>
<table class='table table-hover'>
  <thead>
  <tr>
    <th class="col-sm-2"><%= is_inbox ? t('messages.inbox.table.th_from') : t('messages.inbox.table.th_to')  %></th>
    <th><%= t('messages.inbox.table.th_subject') %></th>
    <th class="col-sm-3"><%= t('messages.inbox.table.th_created_at') %></th>
    <% if is_inbox %>
      <th class="col-sm-1"><%= t('messages.inbox.table.th_actions') %></th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @messages.each do |message| %>
    <tr <%= raw('class="warning"') if message.unread %> style="cursor:pointer;">
      <td onclick="location.href='<%= message_path(message) %>'" >
        <% if is_inbox %>
          <%= link_to message.from, user_path_by_email(message.from) %></td>
        <% else %>
            <%= link_to message.to, user_path_by_email(message.to) %></td>
        <% end %>
      <td onclick="location.href='<%= message_path(message) %>'" ><%= message.subject %></td>
      <td onclick="location.href='<%= message_path(message) %>'" ><%= message.created_at %></td>
      <% if is_inbox %>
      <td>
        <%= link_to t('messages.inbox.btn_destroy'), message, :class => 'btn btn-danger btn-xs',method: :delete, data: { confirm: t('messages.inbox.alert_delete')} %>
      </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/messages/inbox.html.erb
<h4><%= t('messages.inbox.title') %><%= link_to 'New Message', new_message_path, :class => 'btn btn-default pull-right' %></h4>

<%= render 'messages/msg_list' %>

app/views/messages/new.html.erb
<% if @message.errors.any? %>
  <div class="panel panel-danger" id="error_explanation">
    <div class="panel-heading"><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</div>

    <% @message.errors.full_messages.each do |msg| %>
      <div class="panel-body"><%= msg %></div>
    <% end %>
  </div>
  <br/>
<% end %>

<%= form_for(@message, :html => {:role => 'form', :class => 'form-horizontal'}) do |f| %>
  <h4><%= t('messages.new.title') %><button type="submit" class="btn btn-default pull-right"><%= t('messages.new.send') %></button></h4>
  <hr>
  <div class="form-group">
    <%= f.label t('messages.new.to'), :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%# TODO: bug. user is not preselected when replying to message %>
      <%= f.collection_select(:to, recipients, :email, :name_with_email, {:selected => @reply_to}, :class => 'form-control') %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label t('messages.new.subject'), :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :subject, :type => 'text', :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label t('messages.new.content'), :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :content, :type => 'text', :class => 'form-control' %>
    </div>
  </div>
<% end %>

app/views/messages/outbox.html.erb
<h4><%= t('messages.outbox.title') %></h4>

<%= render 'messages/msg_list' %>

app/views/messages/show.html.erb
<% own_message = @message.from == current_user.email %>
<h4>
  <div class="row">
    <div class="col-md-9">
      <span class="msg-header"><%= @message.subject %></span>
    </div>
    <div class="col-md-3">
      <% unless own_message %>
        <%= link_to t('messages.show.btn_destroy'), @message, :class => 'btn btn-danger pull-right', method: :delete, data: { confirm: t('messages.show.alert_delete')} if current_user.email == @message.to %>
        <%= link_to t('messages.show.btn_reply'), new_message_path(:reply_to => @message.from), :class => 'btn btn-default pull-right' %>
      <% end %>
    </div>
  </div>
</h4>
<hr>
<h5><%= "#{t('messages.show.from')} #{@from.fname} #{@from.lname} <#{@message.from}> at #{@message.created_at}" %></h5>
<h5><%= "#{t('messages.show.to')} #{@to.fname} #{@to.lname} <#{@message.to}>" %></h5>
<hr>
<p class="msg-text"><%= simple_format(@message.content) %></p>