config/routes.rb
Messenger::Application.routes.draw do
  resources :password_reset, only: [:new, :edit, :create, :update]

  root :to => 'static_pages#home'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, except: [:index, :update]

  get 'inbox', :to => 'messages#inbox'
  get 'outbox', :to => 'messages#outbox'

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout

end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  skip_filter :require_login

  def new

  end

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    # TODO: bug. no any message after sending password reset mail. just redirect to homepage
    redirect_to(root_path, :notice => t('password_reset.create.notice'))
  end

  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated if !@user
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token] # needed to render the form again in case of error
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if !@user
                            # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
                            # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => t('password_reset.update.success'))
    else
      render :action => 'edit'
    end
  end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/_form.html.erb
<% if @user.errors.any? %>
    <div class= "alert-danger" id="error_explanation">
      <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%# TODO: bug. bad html code %>
<%= form_for @user, :url => password_reset_path, :html => { :class => 'form-signin' } do |f| %>
    <%# TODO: bug. title everywhere is h4. here h2. %>
    <h2 class="form-signin-heading"><%= t('password_reset.edit.title') %></h2>
    <%= f.text_field :password, :class => 'form-control', :required => true, :type => 'password', :autofocus => true, :placeholder => t('password_reset.edit.pwd_new') %>
    <%= f.text_field :password_confirmation, :class => 'form-control',:required => true, :type => 'password', :placeholder => t('password_reset.edit.pwd_confirm') %>
    <%= hidden_field_tag :token, @token %>
    <button type="submit" class="btn btn-lg btn-primary btn-block"><%= t('password_reset.edit.btn_change') %></button>
<% end %>

app/views/password_reset/edit.html.erb
<h4>Reset Password</h4>

<%= render 'form' %>

app/views/password_reset/new.html.erb
<%= form_tag password_reset_index_path, :method => :post, :class => 'form-signin' do %>
  <div class="form-control">
    <%= label_tag :email %><br />
    <%# TODO: bug. incorrect corners for the text field %>
    <%= text_field_tag :email, nil, :class => 'form-control', :required => true %>
    <button type="submit" class="btn btn-lg btn-primary btn-block"><%= t('password_reset.new.btn_reset') %></button>
  </div>
<% end %>