config/routes.rb
Messenger::Application.routes.draw do
  resources :password_reset, only: [:new, :edit, :create, :update]

  root :to => 'static_pages#home'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, except: [:index, :update]

  get 'inbox', :to => 'messages#inbox'
  get 'outbox', :to => 'messages#outbox'

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header_collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t('header.site_title'), root_path, class: 'navbar-brand text-brand-top' %>
  </div>
  <div class="collapse navbar-collapse" id="header_collapse">
    <ul class="nav navbar-nav navbar-right">
      <%= current_user ? render('layouts/header_auth') : render('layouts/header_unauth') %>
    </ul>
  </div>
</nav>

app/views/layouts/_header_auth.html.erb
<li><p class="navtext navbar-link"><%= t('header.signed_in_as') + ' ' + current_user.email %></p></li>
<li><%= link_to t('header.send_message'), new_message_path %></li>
<li><%= link_to raw(t('header.messages') + ' <span class="badge" style="background-color:rgb(217, 83, 79);">' + unread_count.to_s + '</span>'), inbox_path %></li>
<li><%= link_to t('header.edit_profile'), edit_user_path(current_user) %></li>
<li><%= link_to t('header.logout'), logout_path %>

app/views/layouts/_header_unauth.html.erb
<li><%= link_to t('header.login'), login_path %></li>
<li><%= link_to t('header.signup'), new_user_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : t('app_name')  %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container" id="content">
  <div class="flash">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/messages.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : t('app_name')  %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container" id="content">
  <div class="flash">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

  <div class="col-md-2">
    <%= render 'messages/lsidebar' %>
  </div>

  <div class="col-md-10">
    <%= yield %>
  </div>
</div>

</body>
</html>